name: 12 - Working with Outputs

on:
    workflow_dispatch:
        inputs:
            built-status:
                type: choice
                options: [success, failure]
                default: success

jobs:
    build:
        runs-on: ubuntu-latest
        outputs:
            name: ${{steps.build.outputs.status}}
        steps:
            - name: Print GITHUB_OUTPUT path
              run: echo "$GITHUB_OUTPUT"
            - name: Build
              id: build
              run: echo "status=${{inputs.built-status}}" >> "$GITHUB_OUTPUT"
    deploy:
        runs-on: ubuntu-latest
        needs:
            - build
        if: ${{needs.build.outputs.name == 'success'}}
        steps:
            - name: Deploy
              run: echo "Deploying..."