name: 13 - Using Caching
on:
    workflow_dispatch:
        inputs:
            use-cache:
                description: Whether to execute cache step
                type: boolean
                default: true
            node-version:
                description: Node version
                type: choice
                options: [18.x, 20.x, 21.x]
                default: 20.x

jobs:
    build:
        defaults:
            run:
                working-directory: '13-caching/react-app'
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                node-version: '20.x'
            - name: Download cached dependencies
              if: ${{inputs.use-cache}}
              uses: actions/cache@v3
              id: cache
              with:
                path: 13-caching/react-app/node_modules
                key: deps-node-modules-${{hashFiles('13-caching/react-app/package-lock.json')}}
            - name: Install dependencies
              if: steps.cache.outputs.cache-hit != 'true'
              run: npm ci
            - name: Testing
              run: npm run test
            - name: Building
              run: npm run build
            - name: Deploying to nonprod
              run: echo "Deploying to nonprod"