name: 17 - 3 - Custom Actions - Docker
on:
    workflow_dispatch:
        inputs:
            url:
                type: choice
                options: ['https://www.google.com', 'https://doesnt-exist-maybe.com']
            max_trials:
                description: "Maximum trials until action fails"
                default: '5'
            delay:
                description: Delay in seconds between trials
                default: '3'
jobs:
    ping-url:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Ping URL
              uses: ./.github/actions/docker-ping-url
              with:
                url: ${{inputs.url}}
                max_trials: ${{inputs.max_trials}}
                delay: ${{inputs.delay}}