name: 18.2 - Reusable Workflows
on:
    workflow_dispatch:
jobs:
    deploy:
        uses: ./.github/workflows/18-1-reusable-workflows.yaml
        with:
            target-directory: dymmy-dir
    print-outputs:
        runs-on: ubuntu-latest
        needs: deploy
        steps:
            - name: Print Outputs
              run: |
                echo "Build status: ${{needs.deploy.outputs.build-status}}"
                echo "Artifact url: ${{needs.deploy.outputs.url}}"